version : '3.6'

services :
  Directeur:
    image: castermanerobin/posteuserinterne:latest
    container_name: Directeur
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Direction:
        ipv4_address: 172.16.1.2

  Secretaire:
    image: castermanerobin/posteuserinterne:latest
    container_name: Secretaire
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Direction:
        ipv4_address: 172.16.1.3

  comptable1:
    image: castermanerobin/posteuserinterne:latest
    container_name: comptable1
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Administration:
        ipv4_address: 172.16.3.2

  comptable2:
    image: castermanerobin/posteuserinterne:latest
    container_name: comptable2
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Administration:
        ipv4_address: 172.16.3.3

  Commercial1:
    image: castermanerobin/posteuserinterne:latest
    container_name: Commercial1
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Administration:
        ipv4_address: 172.16.3.4

  Commercial2:
    image: castermanerobin/posteuserinterne:latest
    container_name: Commercial2
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Administration:
        ipv4_address: 172.16.3.5

  Atelier1:
    image: castermanerobin/posteuserinterne:latest
    container_name: Atelier1
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Atelier:
        ipv4_address: 172.16.2.2

  Atelier2:
    image: castermanerobin/posteuserinterne:latest
    container_name: Atelier2
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Atelier:
        ipv4_address: 172.16.2.3

networks:
  Direction:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
  Administration:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.3.0/24
  Atelier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24

