version: "3"

services:
  soa:
    image: he201706/dns:latest
    container_name: soa
    restart: always
    command: bash -c "chmod a+x /etc/bind/dnssec_key.sh && /etc/bind/dnssec_key.sh && rm /etc/bind/dnssec_key.sh"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./conf/named.conf:/etc/bind/named.conf
      - ./conf/named.conf.options:/etc/bind/named.conf.options
      - ./conf/named.conf.local:/etc/bind/named.conf.local
      - ./conf/db.l2-7.ephec-ti.be:/etc/bind/db.l2-7.ephec-ti.be
      - ./conf/dnssec_key.sh:/etc/bind/dnssec_key.sh
