version: '3'

services:
  db:
    image: he201706/db:latest
    command: ["--default-authentication-plugin=mysql_native_password", "--init-file /data/application/init.sql"]
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: user1234
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: user1234
    volumes:
      - ./scripts/test.sql:/test.sql
