version : '3.6'

services :
 maildb:
    image : mysql:5.7
    container_name: db
    tty : true
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    
    volumes:
      - ./sql-scripts:/home
    ports :
      - "3306:3306"
    environment :
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mailserver
      MYSQL_USER: mailuser
      MYSQL_PASSWORD: ****
