version: "3"

services:
  soa:
    image: he201706/dns:latest
    container_name: soa
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"

  web:
    image: he201706/web:latest
    container_name: web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot

  php:
    image: he201706/php:latest
    container_name: php
    volumes:
      - ./web/index.php:/usr/share/nginx/html/b2b/index.php

  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot

  db:
    image: he201706/db:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment :
      MYSQL_ROOT_PASSWORD: ****
      MYSQL_DATABASE: ****
      MYSQL_USER: ****
      MYSQL_PASSWORD: ****
