version: "3"

services:
  soa:
    image: he201706/dns:latest
    container_name: soa
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"

  web:
    image: he201706/web:latest
    container_name: web
    restart: always
    ports:
      - "80:80"
      - "443:443"

  php:
    image: he201706/php:latest
    volumes:
      - ./web/index.php:/usr/share/nginx/html/b2b/index.php

  db:
    image: he201706/db:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment :
      MYSQL_ROOT_PASSWORD: ****
      MYSQL_DATABASE: ****
      MYSQL_USER: ****
      MYSQL_PASSWORD: ****
