version: "3"

services:
  soa:
    image: he201706/dns:latest
    container_name: soa
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns/conf/named.conf:/etc/bind/named.conf
      - ./dns/conf/named.conf.options:/etc/bind/named.conf.options
      - ./dns/conf/named.conf.local:/etc/bind/named.conf.local
      - ./dns/conf/db.l2-7.ephec-ti.be:/etc/bind/db.l2-7.ephec-ti.be

  web:
    image: he201706/web:latest
    container_name: web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web/sites/index.html:/usr/share/nginx/html/index.html